### ISSUE TITLE
Classification accuracy of the model

### ISSUE THREAD

**Issue by ylfzr** [flrngel/cpc-tensorflow#4]
Hi, 
I wonder if there is any hint on the final classification accuracy on the cpc representations. (One linear classifier built on top of the well-extracted cpc-features). I ran the code but only got around 25% accuracy on the FASHION_MNIST data after 30000 iters training in the final evaluation, which is weird. 

There might be something wrong with my experiment, is here any thing that I should pay more attention run the code? I just directly run the model, train the cpc feature extractor and then set "mode" to be "validation"  and train the final classifier.

**Comment by flrngel** [comment]
Default code makes 47% accuracy
Thinking about method which use to be input for CPC and validation is to see cpc is working (which means freezing the model), performance of 47% seems awful but acceptable
